# Dark power {{{

[[plugins]]
repo = 'Shougo/dein.vim'

# }}}

# Visual {{{

[[plugins]]
repo = 'cohama/easy-colorcolumn'

[[plugins]]
repo = 'itchyny/thumbnail.vim'

[[plugins]]
repo = 'osyo-manga/vim-brightest'

[[plugins]]
repo = 'rhysd/inazuma.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 't9md/vim-quickhl'

[[plugins]]
repo = 'thinca/vim-zenspace'

[[plugins]]
repo = 'VOom'

[[plugins]]
repo = 'Yggdroot/indentLine'

# }}}

# Benri {{{

[[plugins]]
repo = 'haya14busa/niconicomment.vim'

# [[plugins]]
# repo = 'tyru/banban.vim'
# if = 'has("gui_running")'

# }}}

# Corpse Blinder {{{

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'popkirby/lightline-iceberg'


[[plugins]]
repo = 'freeo/vim-kalisi'

[[plugins]]
repo = 'aereal/vim-colors-japanesque'

# }}}

# Completion {{{

[[plugins]]
repo = 'mattn/googlesuggest-complete-vim'

[[plugins]]
repo = 'mattn/sonictemplate-vim'

[[plugins]]
repo = 'mattn/sonictemplate-vim'

[[plugins]]
repo = 'Shougo/neocomplete'

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'ujihisa/neco-look'

# [[plugins]]
# repo = 'cohama/lexima.vim'

# [[plugins]]
# repo = 'Valloric/YouCompleteMe' ", {'build': {'unix' : './install.sh'}}

# }}}

# Development {{{

[[plugins]]
repo = 'AndrewRadev/linediff.vim'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'thinca/vim-qfreplace'

[[plugins]]
repo = 'scrooloose/syntastic.git'

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'cohama/vim-hier'

# }}}

# Filetype {{{

# filetype / syntax / indent
[[plugins]]
repo = 'chase/vim-ansible-yaml'

[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'freitass/todo.txt-vim'

[[plugins]]
repo = 'Matt-Deacalion/vim-systemd-syntax'

[[plugins]]
repo = 'toshi32tony3/vim-trailing-whitespace'

[[plugins]]
repo = 'rcmdnk/vim-markdown'

[[plugins]]
repo = 'sudar/vim-arduino-syntax'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'lfe-support/vim-lfe'

# (Java|ECMA|Type)Script
[[plugins]]
repo = 'salomvary/vim-eslint-compiler'


# Haskell
[[plugins]]
repo = 'bitc/lushtags'

[[plugins]]
repo = 'dag/vim2hs'

[[plugins]]
repo = 'eagletmt/unite-haddock'

[[plugins]]
repo = 'ujihisa/unite-haskellimport'

# [[plugins]]
# repo = 'eagletmt/ghcmod-vim'

# [[plugins]]
# repo = 'ujihisa/neco-ghc'


# Common Lisp
[[plugins]]
repo = 'mopemope/unite-hyperspec'

# [[plugins]]
# repo = 'vim-scripts/slimv.vim' " vim update issue s:


# Clojure
[[plugins]]
repo = 'thinca/vim-ft-clojure'

[[plugins]]
repo = 'ujihisa/neoclojure.vim'

# Lisp
[[plugins]]
repo = 'guns/vim-sexp'

# [[plugins]]
# repo = 'paredit.vim'


# Scala
[[plugins]]
repo = 'derekwyatt/vim-scala'


# }}}

# Formatter {{{

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

# }}}

# Game {{{

[[plugins]]
repo = 'katono/rogue.vim'

[[plugins]]
repo = 'mattn/flappyvird-vim'

[[plugins]]
repo = 'mattn/habatobi-vim'

[[plugins]]
repo = 'mattn/invader-vim'

[[plugins]]
repo = 'thinca/vim-threes'

[[plugins]]
repo = 'progressbar-widget'

# [[plugins]]
# repo = 'mattn/die-vim'

# }}}

# Information {{{

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'KazuakiM/vim-qfstatusline'

[[plugins]]
repo = 'manicmaniac/betterga'

# [[plugins]]
# repo = 'majutsushi/tagbar'

# }}}

# Library {{{

[[plugins]]
repo = 'haya14busa/vim-migemo'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'vim-jp/vital.vim'

# }}}

# Metarw {{{

[[plugins]]
repo = 'kana/vim-metarw'

[[plugins]]
repo = 'mattn/vim-metarw-gdrive'

# }}}

# Net {{{

[[plugins]]
repo = 'basyura/J6uil.vim'

[[plugins]]
repo = 'heavenshell/vim-slack'

# }}}

# Operator {{{

[[plugins]]
repo = 'kana/vim-operator-replace'

[[plugins]]
repo = 'wellle/targets.vim'

[[plugins]]
repo = 'tommcdo/vim-exchange'

# }}}

# Search And Destroy {{{

[[plugins]]
repo = 'haya14busa/incsearch.vim'

[[plugins]]
repo = 'haya14busa/vim-asterisk'

[[plugins]]
repo = 'osyo-manga/vim-over'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'tyru/chdir-proj-root.vim'

[[plugins]]
repo = 'vim-scripts/gtags.vim'

# }}}

# Shell {{{

[[plugins]]
repo = 'b4b4r07/vim-shellutils'

[[plugins]]
repo = 'Shougo/vimshell'

# }}}

# Sticky Fingers {{{

[[plugins]]
repo = 'AndrewRadev/switch.vim'

[[plugins]]
repo = 'deris/vim-rengbang'

[[plugins]]
repo = 'gcmt/wildfire.vim'

[[plugins]]
repo = 'kana/vim-niceblock'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'thinca/vim-portal'

[[plugins]]
repo = 't9md/vim-textmanip'

[[plugins]]
repo = 'tyru/vim-altercmd'

# }}}

# Text Object {{{

#     b   = Any brackets
#     fX  = beetween X - http://d.hatena.ne.jp/thinca/20100614/1276448745
#     i   = Indent Level
#     u   = URL
#     y   = Syntax
#     z   = Fold
[[plugins]]
repo = 'kana/vim-textobj-fold'

[[plugins]]
repo = 'kana/vim-textobj-indent'

[[plugins]]
repo = 'kana/vim-textobj-syntax'

[[plugins]]
repo = 'mattn/vim-textobj-url'

[[plugins]]
repo = 'osyo-manga/vim-textobj-multiblock'

# }}}

# Tool {{{

[[plugins]]
repo = 'tasuten/gcalc.vim'

[[plugins]]
repo = 'Shougo/vinarise'

# }}}

# Unplugged {{{

[[plugins]]
repo = 'LeafCage/nebula.vim'

[[plugins]]
repo = 'thinca/vim-editvar'

[[plugins]]
repo = 'thinca/vim-prettyprint'

[[plugins]]
repo = 'tyru/capture.vim'

[[plugins]]
repo = 'tyru/foldballoon.vim'

# }}}

# Ref {{{

[[plugins]]
repo = 'phongvcao/vim-stardict'

[[plugins]]
repo = 'taka84u9/vim-ref-ri'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'ujihisa/ref-hoogle'

[[plugins]]
repo = 'rhysd/devdocs.vim'

# }}}

# Unite {{{

[[plugins]]
repo = 'lambdalisue/unite-grep-vcs'

[[plugins]]
repo = 'mattn/httpstatus-vim'

[[plugins]]
repo = 'mattn/unite-mpc'

[[plugins]]
repo = 'osyo-manga/unite-nyancat_anim'

[[plugins]]
repo = 'osyo-manga/unite-quickfix'

[[plugins]]
repo = 'osyo-manga/unite-quickrun_config'

[[plugins]]
repo = 'rhysd/unite-stackoverflow.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/unite-help'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'thinca/vim-unite-history'

[[plugins]]
repo = 'tsukkee/unite-tag'

[[plugins]]
repo = 'ujihisa/unite-colorscheme'

[[plugins]]
repo = 'ujihisa/unite-locate'

# }}}

# VCS {{{

[[plugins]]
repo = 'cohama/agit.vim'

[[plugins]]
repo = 'hrsh7th/vim-unite-vcs'

[[plugins]]
repo = 'kmnk/vim-unite-giti'

[[plugins]]
repo = 'lambdalisue/vim-gista'

[[plugins]]
repo = 'lambdalisue/vim-gita'

[[plugins]]
repo = 'rhysd/committia.vim'

[[plugins]]
repo = 'rhysd/git-messenger.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

# }}}

# Vim {{{

[[plugins]]
repo = 'mattn/benchvimrc-vim'

[[plugins]]
repo = 'thinca/vim-ambicmd'

[[plugins]]
repo = 'thinca/vim-fontzoom'

[[plugins]]
repo = 'thinca/vim-localrc'

[[plugins]]
repo = 'thinca/vim-scouter'

[[plugins]]
repo = 'tyru/restart.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'todesking/vint-syntastic'

[[plugins]]
repo = 'violetyk/gitquick.vim'

# }}}

# Misc {{{

[[plugins]]
repo = 'sjl/gundo.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'Konfekt/FastFold'

[[plugins]]
repo = 'yuratomo/gmail.vim'

[[plugins]]
repo = 'anekos/runes-vim'

# [[plugins]]
# repo = 'tyru/eskk.vim'

# }}}

# White Zombie {{{

[[plugins]]
repo = 'LeafCage/alti.vim'

# }}}

# Our {{{

[[plugins]]
repo = 'anekos/felis-cat-igirisu-toast-express'

[[plugins]]
repo = 'anekos/runes-vim'

[[plugins]]
repo = 'anekos/manga-osort'

[[plugins]]
repo = 'anekos/unite-font'

[[plugins]]
repo = 'anekos/commandlinefu.vim'

[[plugins]]
repo = 'anekos/unite-located-session'

[[plugins]]
name = 'liname-hs'
repo = 'anekos/liname-hs'
rtp = 'res/vim'

# [[plugins]]
# name = 'xmonad'
# repo = '~/.xmonad/res/vim'

# }}}
